alias aliases='sudo vi .bash_aliases'
alias ..='cd ..'
alias knake='OLDIR=`pwd`; roscd; .. && catkin_make && cd $OLDIR'
alias vbash='vim ~/.bashrc'
alias sbash='source ~/.bashrc'
alias tlist='rostopic list'
alias plist='rosparam list'
alias tinfo='rostopic info'
alias techo='rostopic echo'
alias sshsparus='ssh -XY -t sparus@192.168.1.205 "byobu -S eric" '
alias sshbuoy='ssh -XY -t pi@192.168.1.200 "byobu -S eric"'
alias sshpi='ssh -XY -t pi@192.168.1.100 "byobu -S eric"' 
alias sshproy='ssh -XY -t pi@192.168.1.30 "byobu -S eric"'
alias plot_odometry='roscd stereo_slam && ./scripts/plot_odom.py L /ekf_odom/odometry /ekf_map/odometry /sparus/ros_odom_to_pat'
alias plot_odometry2='roscd stereo_slam && ./scripts/plot_odom.py L /camera_pose'
alias gits='git status'
alias gitp='git pull'

